#Using version 2.4 because the condition block of the depends_on option was removed as of 3.0
version: '2.4'

services:
  db:
    container_name: meleeNeat-database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: meleeNeat
    volumes:
      - /data:/opt/data
      - meleeNeat-db-data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"USE werewolf;\""
      interval: 20s
      timeout: 10s
      retries: 6

  adminer:
    container_name: meleeNeatadminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # werewolf-gameserver:
  #   image: sped/werewolf-gameserver:latest
  #   container_name: werewolf-gameserver
  #   environment:
  #   - KTOR_ENV=local
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     db:
  #       condition: service_healthy
volumes:
  meleeNeat-db-data:
    name: meleeNeat-db-data